columns:
  NumDots: int64
  UrlLength: int64
  NumDash: int64
  AtSymbol: int64
  IpAddress: int64
  HttpsInHostname: int64
  PathLevel: int64
  PathLength: int64
  NumNumericChars: int64
  Phising: int64

numerical_columns:
  - NumDots
  - UrlLength
  - NumDash
  - AtSymbol
  - IpAddress
  - HttpsInHostname
  - PathLevel
  - PathLength
  - NumNumericChars

target_column: Phising














# columns:
#   having_IP_Address: int64
#   URL_Length: int64
#   Shortining_Service: int64
#   having_At_Symbol: int64
#   double_slash_redirecting: int64
#   prefix_Suffix: int64
#   having_Sub_Domain: int64
#   SSLfinal_State: int64
#   Domain_registeration_length: int64
#   Favicon: int64
#   port: int64
#   HTTPS_token: int64
#   Request_URL: int64
#   URL_of_anchor: int64
#   Links_in_tags: int64
#   SFH: int64
#   submitting_to_email: int64
#   Abnormal_URL: int64
#   Redirect: int64
#   on_mouseover: int64
#   RightClick: int64
#   popUpWindnow: int64
#   Iframe: int64
#   age_of_domain: int64
#   DNSRecord: int64
#   web_traffic: int64
#   Page_Rank: int64
#   Google_Index: int64
#   Links_pointing_to_page: int64
#   Statistical_report: int64
#   Result: int64

# numerical_columns:
#   - having_IP_Address
#   - URL_Length
#   - Shortining_Service
#   - having_At_Symbol
#   - double_slash_redirecting
#   - prefix_Suffix
#   - having_Sub_Domain
#   - SSLfinal_State
#   - Domain_registeration_length
#   - Favicon
#   - port
#   - HTTPS_token
#   - Request_URL
#   - URL_of_anchor
#   - Links_in_tags
#   - SFH
#   - submitting_to_email
#   - Abnormal_URL
#   - Redirect
#   - on_mouseover
#   - RightClick
#   - popUpWindnow
#   - Iframe
#   - age_of_domain
#   - web_traffic
#   - Page_Rank
#   - Google_Index
#   - Links_pointing_to_page
#   - Statistical_report
#   - Result






# columns:
#   Unnamed: 0: int
#   NumDots: int
#   UrlLength: int
#   NumDash: int
#   AtSymbol: int
#   IpAddress: int
#   HttpsInHostname: int
#   PathLevel: int
#   PathLength: int
#   NumNumericChars: int
#   Phising: int




